/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CertificateRegistry {
      
    export type CertificateRecordStruct = {certHash: BytesLike, issuer: AddressLike, issuedAt: BigNumberish, revoked: boolean}

    export type CertificateRecordStructOutput = [certHash: string, issuer: string, issuedAt: bigint, revoked: boolean] & {certHash: string, issuer: string, issuedAt: bigint, revoked: boolean }
  
    }

  export interface CertificateRegistryInterface extends Interface {
    getFunction(nameOrSignature: "authorizeIssuer" | "authorizedIssuers" | "deauthorizeIssuer" | "exists" | "getCertificate" | "issueCertificate" | "owner" | "revokeCertificate"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateIssued" | "CertificateRevoked" | "IssuerAuthorized" | "IssuerDeauthorized"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizeIssuer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'authorizedIssuers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deauthorizeIssuer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'exists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getCertificate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'issueCertificate', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeCertificate', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'authorizeIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedIssuers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deauthorizeIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCertificate', data: BytesLike): Result;
  }

  
    export namespace CertificateIssuedEvent {
      export type InputTuple = [certIdHash: BytesLike, certHash: BytesLike, issuer: AddressLike, issuedAt: BigNumberish];
      export type OutputTuple = [certIdHash: string, certHash: string, issuer: string, issuedAt: bigint];
      export interface OutputObject {certIdHash: string, certHash: string, issuer: string, issuedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CertificateRevokedEvent {
      export type InputTuple = [certIdHash: BytesLike, issuer: AddressLike];
      export type OutputTuple = [certIdHash: string, issuer: string];
      export interface OutputObject {certIdHash: string, issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssuerAuthorizedEvent {
      export type InputTuple = [issuer: AddressLike];
      export type OutputTuple = [issuer: string];
      export interface OutputObject {issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssuerDeauthorizedEvent {
      export type InputTuple = [issuer: AddressLike];
      export type OutputTuple = [issuer: string];
      export interface OutputObject {issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CertificateRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): CertificateRegistry;
    waitForDeployment(): Promise<this>;

    interface: CertificateRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizeIssuer: TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedIssuers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    deauthorizeIssuer: TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    exists: TypedContractMethod<
      [certIdHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getCertificate: TypedContractMethod<
      [certIdHash: BytesLike, ],
      [CertificateRegistry.CertificateRecordStructOutput],
      'view'
    >
    

    
    issueCertificate: TypedContractMethod<
      [certIdHash: BytesLike, certHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revokeCertificate: TypedContractMethod<
      [certIdHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizeIssuer'): TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedIssuers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deauthorizeIssuer'): TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [certIdHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getCertificate'): TypedContractMethod<
      [certIdHash: BytesLike, ],
      [CertificateRegistry.CertificateRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'issueCertificate'): TypedContractMethod<
      [certIdHash: BytesLike, certHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revokeCertificate'): TypedContractMethod<
      [certIdHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CertificateIssued'): TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
getEvent(key: 'CertificateRevoked'): TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
getEvent(key: 'IssuerAuthorized'): TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
getEvent(key: 'IssuerDeauthorized'): TypedContractEvent<IssuerDeauthorizedEvent.InputTuple, IssuerDeauthorizedEvent.OutputTuple, IssuerDeauthorizedEvent.OutputObject>;

    filters: {
      
      'CertificateIssued(bytes32,bytes32,address,uint256)': TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
      CertificateIssued: TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
    

      'CertificateRevoked(bytes32,address)': TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
      CertificateRevoked: TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
    

      'IssuerAuthorized(address)': TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
      IssuerAuthorized: TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
    

      'IssuerDeauthorized(address)': TypedContractEvent<IssuerDeauthorizedEvent.InputTuple, IssuerDeauthorizedEvent.OutputTuple, IssuerDeauthorizedEvent.OutputObject>;
      IssuerDeauthorized: TypedContractEvent<IssuerDeauthorizedEvent.InputTuple, IssuerDeauthorizedEvent.OutputTuple, IssuerDeauthorizedEvent.OutputObject>;
    
    };
  }