# Generated by Django 5.0.3 on 2026-08-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CERTIFICATE_ISSUED', 'Certificate issued'), ('EMAIL_VERIFICATION', 'Email verification'), ('PASSWORD_RESET', 'Password reset')], default='CERTIFICATE_ISSUED', max_length=32)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='certificates.certificate')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['certificate', '-sent_at'], name='notificatio_certifi_ac4694_idx')],
            },
        ),
    ]
