# Generated by Django 5.0.3 on 2026-08-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_public_id', models.CharField(blank=True, db_index=True, help_text='Denormalised BCIP certificate ID, kept for audit readability.', max_length=100)),
                ('interaction_type', models.CharField(choices=[('ISSUE', 'Issue certificate'), ('REVOKE', 'Revoke certificate'), ('READ', 'Read certificate')], db_index=True, max_length=10)),
                ('succeeded', models.BooleanField(db_index=True, default=False)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_interactions', to='certificates.certificate')),
            ],
            options={
                'db_table': 'blockchain_interaction_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['certificate', '-created_at'], name='blockchain__certifi_7995bf_idx')],
            },
        ),
    ]
