# Generated by Django 5.0.3 on 2026-08-10 12:29

import certificates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=certificates.models.generate_certificate_id, editable=False, help_text='Public identifier. Appears in the PDF, the QR code and the URL.', max_length=100, unique=True)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('course_title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('certificate_hash', models.CharField(blank=True, db_index=True, max_length=66)),
                ('pdf_sha256', models.CharField(blank=True, max_length=66)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66)),
                ('blockchain_block_number', models.BigIntegerField(blank=True, null=True)),
                ('anchored_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.CharField(blank=True, help_text='Path relative to MEDIA_ROOT, e.g. pdfs/CERT-ABC123.pdf', max_length=500)),
                ('failure_reason', models.TextField(blank=True)),
                ('issuance_attempts', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66)),
                ('confirmed_on_chain', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revocation', to='certificates.certificate')),
                ('revoked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revocation_logs',
                'ordering': ['-revoked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['organization', '-created_at'], name='certificate_organiz_d3c532_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['organization', 'status'], name='certificate_organiz_f93742_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status', 'created_at'], name='certificate_status_ce5798_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('organization', 'idempotency_key'), name='unique_idempotency_key_per_organization'),
        ),
    ]
